# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30c3aaf1f2502661653a07acb6cbb8703732e251435de9ba6876eacb59b17bf22aa82a5f85b3943bfd1d502af635ef3e21a700555eed7d331c89ba6ddb00ba1c

test:
  secret_key_base: 54a852bafcd251846df38014a5d62f03fbf2b2551c197060bb4d54d2af0c17431abf4cd046e95be79e6bd1766fcb7bc238f28d48cecba2f73aba4fd90df08cb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
